// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tb__xbar_connect generated by `tlgen.py` tool

xbar_ifetch dut();

`DRIVE_CLK(clk_sys_i)

initial force dut.clk_sys_i = clk_sys_i;

// TODO, all resets tie together
initial force dut.rst_sys_ni = rst_n;

// Host TileLink interface connections
`CONNECT_TL_HOST_IF(ibex_ifetch, dut, clk_sys_i, rst_n)

// Device TileLink interface connections
`CONNECT_TL_DEVICE_IF(sram, dut, clk_sys_i, rst_n)
`CONNECT_TL_DEVICE_IF(hyperram, dut, clk_sys_i, rst_n)
`CONNECT_TL_DEVICE_IF(dbg_dev, dut, clk_sys_i, rst_n)
