// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main_bind module generated by `tlgen.py` tool for assertions
module xbar_main_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_ibex_lsu (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_ibex_lsu_i),
    .d2h    (tl_ibex_lsu_o)
  );
  bind xbar_main tlul_assert #(.EndpointType("Device")) tlul_assert_host_dbg_host (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_dbg_host_i),
    .d2h    (tl_dbg_host_o)
  );

  // Device interfaces
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_sram_o),
    .d2h    (tl_sram_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_hyperram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_hyperram_o),
    .d2h    (tl_hyperram_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rev_tag (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rev_tag_o),
    .d2h    (tl_rev_tag_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_gpio (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_gpio_o),
    .d2h    (tl_gpio_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_pinmux (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_pinmux_o),
    .d2h    (tl_pinmux_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rgbled_ctrl (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rgbled_ctrl_o),
    .d2h    (tl_rgbled_ctrl_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_hw_rev (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_hw_rev_o),
    .d2h    (tl_hw_rev_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_xadc (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_xadc_o),
    .d2h    (tl_xadc_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_system_info (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_system_info_o),
    .d2h    (tl_system_info_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_timer (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_timer_o),
    .d2h    (tl_timer_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_spi_lcd (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_spi_lcd_o),
    .d2h    (tl_spi_lcd_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_spi_ethmac (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_spi_ethmac_o),
    .d2h    (tl_spi_ethmac_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_pwm0 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_pwm0_o),
    .d2h    (tl_pwm0_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_uart0 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_uart0_o),
    .d2h    (tl_uart0_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_uart1 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_uart1_o),
    .d2h    (tl_uart1_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_uart2 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_uart2_o),
    .d2h    (tl_uart2_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_i2c0 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_i2c0_o),
    .d2h    (tl_i2c0_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_i2c1 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_i2c1_o),
    .d2h    (tl_i2c1_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_spi0 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_spi0_o),
    .d2h    (tl_spi0_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_spi1 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_spi1_o),
    .d2h    (tl_spi1_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_spi2 (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_spi2_o),
    .d2h    (tl_spi2_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_flash_xip_reg (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_flash_xip_reg_o),
    .d2h    (tl_flash_xip_reg_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_usbdev (
    .clk_i  (clk_usb_i),
    .rst_ni (rst_usb_ni),
    .h2d    (tl_usbdev_o),
    .d2h    (tl_usbdev_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_dbg_dev (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_dbg_dev_o),
    .d2h    (tl_dbg_dev_i)
  );
  bind xbar_main tlul_assert #(.EndpointType("Host")) tlul_assert_device_rv_plic (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_rv_plic_o),
    .d2h    (tl_rv_plic_i)
  );
`endif
endmodule
