// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_ifetch_bind module generated by `tlgen.py` tool for assertions
module xbar_ifetch_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_ifetch tlul_assert #(.EndpointType("Device")) tlul_assert_host_ibex_ifetch (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_ibex_ifetch_i),
    .d2h    (tl_ibex_ifetch_o)
  );

  // Device interfaces
  bind xbar_ifetch tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_sram_o),
    .d2h    (tl_sram_i)
  );
  bind xbar_ifetch tlul_assert #(.EndpointType("Host")) tlul_assert_device_hyperram (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_hyperram_o),
    .d2h    (tl_hyperram_i)
  );
  bind xbar_ifetch tlul_assert #(.EndpointType("Host")) tlul_assert_device_dbg_dev (
    .clk_i  (clk_sys_i),
    .rst_ni (rst_sys_ni),
    .h2d    (tl_dbg_dev_o),
    .d2h    (tl_dbg_dev_i)
  );
`endif
endmodule
