// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vspi_eth_tb_top.h for the primary calling header

#ifndef VERILATED_VSPI_ETH_TB_TOP___024ROOT_H_
#define VERILATED_VSPI_ETH_TB_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vspi_eth_tb_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vspi_eth_tb_top___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk_i,0,0);
        VL_IN8(clk_25mhz,0,0);
        CData/*0:0*/ spi_eth_tb_top__DOT____Vcellinp__u_ksz__csn;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rst_ni;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_q;
        VL_IN8(rst_i,0,0);
        VL_IN8(wb_sel_i,3,0);
        VL_IN8(wb_we_i,0,0);
        VL_IN8(wb_cyc_i,0,0);
        VL_IN8(wb_stb_i,0,0);
        VL_OUT8(wb_ack_o,0,0);
        VL_IN8(rx_data,7,0);
        VL_IN8(rx_valid,0,0);
        VL_IN8(rx_last,0,0);
        CData/*0:0*/ spi_eth_tb_top__DOT__spi_cipo;
        CData/*0:0*/ spi_eth_tb_top__DOT__ksz_tx_last;
        CData/*0:0*/ spi_eth_tb_top__DOT__ksz_intrn;
        CData/*3:0*/ spi_eth_tb_top__DOT__ksz_chip_state;
        CData/*7:0*/ spi_eth_tb_top__DOT__ksz_cmd_byte0;
        CData/*7:0*/ spi_eth_tb_top__DOT__ksz_cmd_byte1;
        CData/*0:0*/ spi_eth_tb_top__DOT__ksz_read_pulse;
        CData/*0:0*/ spi_eth_tb_top__DOT__ksz_write_pulse;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__is_tx;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__wb_req;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__ack_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__buf_rd_pending;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__reg_wr;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__cs_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__intr_complete;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__intr_enable_complete;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__spi_data_out;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__spi_data_in_ready;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__spi_start;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__spi_idle_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_cpu_req;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_cpu_req;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__is_reg_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__is_tx_q;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_byte_lane_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_data_valid;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_fetch_pending;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_wr_pending;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_byte_data;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_b_be;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT____VdfgRegularize_h28ad532a_1_2;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__state_q;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__state_d;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__output_edge;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__sample_edge;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__start_edge;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__finish_edge;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_d;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__sample_phase_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__sample_phase_d;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_count_q;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_count_d;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__copi_shift_q;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__copi_shift_d;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__cipo_shift_q;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__cipo_shift_d;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__data_out_valid_q;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_running;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__spi_state_reg;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__opcode;
    };
    struct {
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__reg_addr;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__bit_counter;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__addr_high;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__write_pulse_old;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_enable;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_enable;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__promiscuous_mode;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_first;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_next;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_last;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_avail;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_start_pending;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_busy;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_writing;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_header_count;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_advance;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_reading;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_auto_release_pending;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__byte_sync;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_axis_tdata;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_axis_tvalid;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_axis_tlast;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__irq_rx_enable;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__irq_tx_enable;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__sync;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_enable_old;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_toggle;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_toggle;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync1;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync2;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync3;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync1;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync2;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync3;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_valid_old;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__read_addr;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_byte_out;
        CData/*2:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_bit_count;
        CData/*2:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__state_reg;
        CData/*2:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__state_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__reset_crc;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__update_crc;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__mii_odd;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__mii_locked;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rxd_d0;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rxd_d1;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rxd_d2;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rxd_d3;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rxd_d4;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_dv_d0;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_dv_d1;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_dv_d2;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_dv_d3;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_dv_d4;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_er_d0;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_er_d1;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_er_d2;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_er_d3;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__gmii_rx_er_d4;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tdata_reg;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tdata_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tvalid_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tvalid_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tlast_reg;
    };
    struct {
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tlast_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tuser_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__output_axis_tuser_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__error_bad_frame_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__error_bad_frame_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__error_bad_fcs_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__error_bad_fcs_next;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__crc_cnt;
        CData/*1:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__crc_cnt_next;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__data_out;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__data_val;
        CData/*2:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__state_reg;
        CData/*2:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__state_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__reset_crc;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__update_crc;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__input_tdata_reg;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__input_tdata_next;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__ifg_reg;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__ifg_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__mii_odd_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__mii_odd_next;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__mii_msn_reg;
        CData/*3:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__mii_msn_next;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_txd_reg;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_txd_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_tx_en_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_tx_en_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_tx_er_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__gmii_tx_er_next;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__input_axis_tready_reg;
        CData/*0:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__input_axis_tready_next;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__data_out;
        CData/*7:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__data_val;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__0__Vfuncout;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__0__in;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__0__out;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__1__Vfuncout;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__1__in;
        CData/*7:0*/ __Vfunc_spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__bit_reverse__1__out;
        CData/*7:0*/ __Vdlyvval__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v0;
        CData/*0:0*/ __Vdlyvset__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v0;
        CData/*3:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_next;
        CData/*3:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_packet_length__v0;
        CData/*0:0*/ __Vdlyvset__spi_eth_tb_top__DOT__u_ksz__DOT__rx_packet_length__v0;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_toggle;
        CData/*0:0*/ __Vdlyvset__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v1;
        CData/*7:0*/ __Vdlyvval__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v7;
        CData/*7:0*/ __Vdlyvval__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v8;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_start_pending;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_toggle;
        CData/*3:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__spi_state_reg;
        CData/*7:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__bit_counter;
        CData/*1:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__opcode;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__ksz_write_pulse;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync1;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync2;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_int_sync3;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync1;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync2;
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_int_sync3;
        CData/*1:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_header_count;
        CData/*7:0*/ __Vdlyvval__spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_mem__v0;
        CData/*0:0*/ __Vdlyvset__spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_mem__v0;
        CData/*3:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_buf_first;
    };
    struct {
        CData/*0:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_auto_release_pending;
        CData/*2:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_bit_count;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_i__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__spi_eth_tb_top__DOT__u_spi_wb__DOT__rst_ni__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk_25mhz__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__spi_eth_tb_top__DOT____Vcellinp__u_ksz__csn__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_q__0;
        CData/*3:0*/ __Vtrigprevexpr___TOP__spi_eth_tb_top__DOT__ksz_chip_state__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        VL_IN16(wb_adr_i,12,0);
        SData/*11:0*/ spi_eth_tb_top__DOT__ksz_rx_byte_count;
        SData/*11:0*/ spi_eth_tb_top__DOT__ksz_tx_byte_count;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__buf_byte_addr;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_count;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_byte_addr;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_counter_q;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__clk_counter_d;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__byte_count_q;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__u_spi_core__DOT__byte_count_d;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_MARL;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_MARM;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_MARH;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_TXCR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_TXSR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXCR1;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXCR2;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_TXMIR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXFHSR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXFHBCR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_TXQCR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXQCR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_TXFDPR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXFDPR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_IER;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_ISR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_RXFCTR;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__register_CIDER;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__shift_reg_in;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__shift_reg_out;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__write_data;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_packet_length;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_frame_addr;
        SData/*14:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_wr_ptr;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_frame_length;
        SData/*14:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_wr_ptr;
        SData/*14:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_rd_ptr;
        SData/*14:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_frame_start;
        SData/*10:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_addr_axis;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__reg_read;
        SData/*14:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__unnamedblk1__DOT__frame_end_pos;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__frame_ptr_reg;
        SData/*15:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__frame_ptr_next;
        SData/*10:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_frame_addr;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v0;
        SData/*10:0*/ __Vdlyvval__spi_eth_tb_top__DOT__u_ksz__DOT__rx_packet_length__v0;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v1;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v2;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v3;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v4;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v5;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v6;
    };
    struct {
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v7;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem__v8;
        SData/*14:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_wr_ptr;
        SData/*14:0*/ __Vdlyvdim0__spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_mem__v0;
        SData/*15:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__write_data;
        SData/*15:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__register_ISR;
        SData/*14:0*/ __Vdly__spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_rd_ptr;
        VL_IN(wb_dat_i,31,0);
        VL_OUT(wb_dat_o,31,0);
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__cfg_reg;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__reg_rdata_q;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_cpu_rdata;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_cpu_rdata;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__tx_bram_rdata;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_b_wdata;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_spi_wb__DOT__rx_bram_unused_rdata;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rxfhsr_t;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rxqcr_t;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__txqcr_t;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_fcs_reg;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fcs_reg;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__tx_fcs_reg_rev;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_fcs_reg_rev;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__i;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__fcs_next;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__crc_state;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__crc_next;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__state_val;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__i;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__j;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__k;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__crc_state;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__fcs_next;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__crc_next;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__state_val;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__i;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__j;
        IData/*31:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__k;
        IData/*31:0*/ __VactIterCount;
        QData/*47:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__mac_address;
        QData/*47:0*/ spi_eth_tb_top__DOT__u_ksz__DOT__rx_dest_mac;
        VlUnpacked<IData/*31:0*/, 512> spi_eth_tb_top__DOT__u_spi_wb__DOT__u_tx_ram__DOT__mem;
        VlUnpacked<IData/*31:0*/, 512> spi_eth_tb_top__DOT__u_spi_wb__DOT__u_rx_ram__DOT__mem;
        VlUnpacked<SData/*10:0*/, 16> spi_eth_tb_top__DOT__u_ksz__DOT__rx_packet_length;
        VlUnpacked<SData/*12:0*/, 16> spi_eth_tb_top__DOT__u_ksz__DOT__rx_frame_start_pos;
        VlUnpacked<CData/*7:0*/, 32768> spi_eth_tb_top__DOT__u_ksz__DOT__tx_fifo_mem;
        VlUnpacked<CData/*7:0*/, 32768> spi_eth_tb_top__DOT__u_ksz__DOT__rx_fifo_mem;
        VlUnpacked<IData/*31:0*/, 32> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__lfsr_mask_state;
        VlUnpacked<CData/*7:0*/, 32> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__lfsr_mask_data;
        VlUnpacked<IData/*31:0*/, 8> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__output_mask_state;
        VlUnpacked<CData/*7:0*/, 8> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_rx_inst__DOT__eth_crc_8__DOT__output_mask_data;
        VlUnpacked<IData/*31:0*/, 32> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__lfsr_mask_state;
        VlUnpacked<CData/*7:0*/, 32> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__lfsr_mask_data;
        VlUnpacked<IData/*31:0*/, 8> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__output_mask_state;
        VlUnpacked<CData/*7:0*/, 8> spi_eth_tb_top__DOT__u_ksz__DOT__gmii_tx_inst__DOT__eth_crc_8__DOT__output_mask_data;
        VlUnpacked<CData/*0:0*/, 14> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<8> __VactTriggered;
    VlTriggerVec<8> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vspi_eth_tb_top__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vspi_eth_tb_top___024root(Vspi_eth_tb_top__Syms* symsp, const char* v__name);
    ~Vspi_eth_tb_top___024root();
    VL_UNCOPYABLE(Vspi_eth_tb_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
